### PR TITLE
Add children prop to Slider.Marker

### PR DESCRIPTION
**Pull request by vasco3**
I needed this prop to pass custom labels element to the markers

### CODE REVIEW

**Comment by eldh** [comment]
It can probably be optional though right?

**Comment by eldh** [comment]
The reach ui docs doesn't mention the marker taking children as a prop, but I assume it works?

**Comment by vasco3** [comment]
good idea, I made it optional.

Yeah it works.. I don't remember how I came up with it but I did put some time browsing the reach-ui repo. 

this is how I am using it 
```reason
<Slider>
  markers->Belt.Array.map(marker =>(
  <Marker key={marker.label} value={marker.factor}>
    <span
        className="block mt-2"
        style={ReactDOMRe.Style.make(~fontSize="8px", ())}>
        marker.label->ReasonReact.string
    </span>
  </Marker>
)->ReasonReact.array
</Slider>
```

And this is the outcome
image

**Comment by eldh** [comment]
Released as 0.3.1

**Comment by eldh** [comment]
Thanks for the PR!

**Pull request merged**
